### ISSUE TITLE
Currency not correctly logged

### ISSUE THREAD

**Issue by ForrestGump83** [adcrafter27/ioBroker.envertech-pv#1]
Obviously currency should be logged also under datapoint ACCURRENCY.
But this Datapoint shows "0" for both of my panels.

Anyway good work so far.

**Comment by adcrafter27** [comment]
Hello on my web interface the datapoint ACCURRENCY always "0"

"Power" is the current generation of AC

![pv_accurrency](https://user-images.githubusercontent.com/15692264/85839960-00894a00-b79c-11ea-8d3f-b3eabd991804.png)
