### ISSUE TITLE
Request for additional Feature (write data to webportal)

### ISSUE THREAD

**Issue by Miskral** [adcrafter27/ioBroker.envertech-pv#215]
I have a request for an additional function. The envertech-pv adapter currently only reads values from the portal and makes them available in the ioBroker. This also works perfectly for me. Many thanks to the developers. 
I am now measuring the power at my grid connection and would like to write these values back into the portal. In detail, these are the two values : 
- **GridPower** 
- **LoadPower**
Maybe there is a simple solution for this. Many thanks for your support.

**Comment by mcm1957** [comment]
I do not know any documented API to write any information to the envertech website. The adapter uses api calls already used at the envertech website.

So I do not see any possibility to implemnt this request.

Do you know any way to write this data i.e. using webbrowser, app, etc. ?

**Comment by mcm1957** [comment]
As there is no known interface to push data to envertechs website I will close here.
