### ISSUE TITLE
Keine Objekte - wo gibt es Debug infos?

### ISSUE THREAD

**Issue by DenisBru** [adcrafter27/ioBroker.envertech-pv#3]
Hi,

ich habe den Adapter angelegt und aus dem Portal die stationid eingetragen. Leider bekomme ich keine Objekte und auch Infos im Log angezeigt. 

Gibt es irgendwo ein entsprechendes Log, damit ich sehen kann, ob der Adapter / die Instanz was macht? 

Hab Version 0.0.7 installiert. 

Meine Umgebung ist leider nicht gerade aktuell, kann es daran liegen? Bisher hat jeder Adapter funktioniert. 
Node.js: v8.16.0
NPM: 6.4.1

LG Denis

**Comment by adcrafter27** [comment]
Normal gibt der Adapter Alle x minuten (eingestellte Minuten) mehrere log Einträge aus.
Also sobald der Adapter von ioBroker gestartet wird kommt eine Meldung.
Hast du mal versucht den gesamten ioBroker neu zu starten?

![image](https://user-images.githubusercontent.com/15692264/89330589-c7909f00-d690-11ea-9f4f-4663d58bdbe3.png)

**Comment by DenisBru** [comment]
Hi... Ich hab iobroker aktualisiert und jetzt läuft es. Davor konnte ich im Log den Adapter nicht auswählen. Er war einfach nicht da.

Jetzt funktioniert es :-) 

Vielen DANK
