### ISSUE TITLE
Fehlermeldung seit Admin 5

### ISSUE THREAD

**Issue by JackDaniel007** [adcrafter27/ioBroker.envertech-pv#8]
<html>
<body>

envertech-pv.0 | 2021-09-07 11:30:02.602 | info | State value to set for "envertech-pv.0.overview.station.InvTotal" has to be type "string" but received type "number"
-- | -- | -- | --
envertech-pv.0 | 2021-09-07 11:30:02.601 | info | State value to set for "envertech-pv.0.overview.station.Etoday" has to be type "string" but received type "number"
envertech-pv.0 | 2021-09-07 11:30:02.601 | info | State value to set for "envertech-pv.0.overview.station.CreateMonth" has to be type "string" but received type "number"
envertech-pv.0 | 2021-09-07 11:30:02.597 | info | State value to set for "envertech-pv.0.overview.station.CreateYear" has to be type "string" but received type "number"
envertech-pv.0 | 2021-09-07 11:30:02.596 | info | State value to set for "envertech-pv.0.overview.station.TimeZone" has to be type "string" but received type "number"
envertech-pv.0 | 2021-09-07 11:30:02.595 | info | State value to set for "envertech-pv.0.overview.station.Lng" has to be type "string" but received type "number"
envertech-pv.0 | 2021-09-07 11:30:02.595 | info | State value to set for "envertech-pv.0.overview.station.Lat" has to be type "string" but received type "number"
envertech-pv.0 | 2021-09-07 11:30:02.594 | info | State value to set for "envertech-pv.0.overview.station.Capacity" has to be type "string" but received type "number"
envertech-pv.0 | 2021-09-07 11:30:02.593 | info | State value to set for "envertech-pv.0.overview.station.Power" has to be type "string" but received type "number"

</body>
</html>

**Comment by adcrafter27** [comment]
Das Problem habe ich bereits behoben, wurde gerade mit 0.0.7 veröffentlicht

**Comment by JackDaniel007** [comment]
danke, funktioniert
